### ISSUE TITLE
[Talk Submission] Stefan Ciancio

### ISSUE THREAD

**Issue by lospoy** [astoria-tech/meetup#137]
### name

Stefan Ciancio

### presentationTitle

How to Turn Your Side Projects into Passive Income

### date

2024-06-05

### slides

[How to Turn Your Side Projects into Passive Income.pdf](https://github.com/user-attachments/files/15594110/How.to.Turn.Your.Side.Projects.into.Passive.Income.pdf)

**Comment by reggi** [comment]
.create-pr
