### ISSUE TITLE
[Talk Submission] Ivan Cortazar

### ISSUE THREAD

**Issue by lospoy** [astoria-tech/meetup#138]
### name

Ivan Cortazar

### presentationTitle

Transforming AI Images into “3D” Trailers

### date

2024-06-05

### slides

[From 2D to 3D v02-compressed.pdf](https://github.com/user-attachments/files/15594158/From.2D.to.3D.v02-compressed.pdf)

**Comment by reggi** [comment]
.create-pr

**Comment by reggi** [comment]
.create-pr
