### ISSUE TITLE
[Talk Submission] Lisa

### ISSUE THREAD

**Issue by SleepyTeaDrinker** [astoria-tech/meetup#144]
### name

Lisa

### linkedin

https://www.linkedin.com/in/lisa-c-2a10224b/

### profileImage

Default image is fine I think

### presentationTitle

So You're Not Running The Meeting...

### slides

[Status report.pptx](https://github.com/user-attachments/files/15796848/Status.report.pptx)

**Comment by azlyth** [comment]
hi there @SleepyTeaDrinker! 👋 

we'll be holding our next meetup on Jan 15th, 2025. if you'd like to give an ~10-minute talk, reach out to me (@pv) on the Astoria Tech Discord! https://astoria.app/links/

happy holidays! 🎄

**Comment by azlyth** [comment]
Closing this in favor of the recent one. ✨
