### ISSUE TITLE
Life after FIRE

### ISSUE THREAD

**Issue by ra9r** [astoria-tech/meetup#47]
### name

Rodney Aiglstorfer

### githubUsername

@ra9r

### linkedIn

https://linkedin.com/in/raiglstorfer

### website

https://lifeafter.fi/

### profileImage

https://media.licdn.com/dms/image/D5603AQHJitWo2wyNow/profile-displayphoto-shrink_200_200/0/1699646638513?e=1718841600&v=beta&t=Dy8TqfZD6JHFwz4scqqy1oZSKVKM-YkKHgE171m430Y

**Comment by reggi** [comment]
.create-pr
