### ISSUE TITLE
AI for the mere mortal web developer

### ISSUE THREAD

**Issue by ashryanbeats** [astoria-tech/meetup#66]
### name

Ash Ryan Arnwine

### githubUsername

ashryanbeats

### linkedin

https://www.linkedin.com/in/ashryan/

### website

https://www.linkedin.com/in/ashryan/

### presentationTitle

AI for the mere mortal web developer

### date

2024-05-01

### slides

Coming soon

**Comment by reggi** [comment]
.create-pr

**Comment by reggi** [comment]
.create-pr

**Comment by reggi** [comment]
you're in

**Comment by ashryanbeats** [comment]
[AI for the mere mortal web developer.pdf](https://github.com/astoria-tech/meetup/files/15178939/AI.for.the.mere.mortal.web.developer.pdf)
