### ISSUE TITLE
[Talk Submission] Ania Stypulkowski

### ISSUE THREAD

**Issue by aniagaska** [astoria-tech/meetup#72]
### name

Ania Stypulkowski

### githubUsername

aniagaska

### linkedin

https://www.linkedin.com/in/annastypulkowski/

### website

http://annastypulkow.ski

### profileImage

![aniagaska](https://github.com/astoria-tech/meetup/assets/44368856/fa3821b4-adfe-4e91-936c-0fb524f2ca30)

### presentationTitle

You deserve some words of encouragement

### date

2024-05-01

### slides

https://peptalk.click/

**Comment by reggi** [comment]
.create-pr

**Comment by reggi** [comment]
this was merged

**Comment by reggi** [comment]
.create-pr

**Comment by reggi** [comment]
.create-pr

**Comment by reggi** [comment]
.create-pr

**Comment by reggi** [comment]
.create-pr
