### ISSUE TITLE
[Talk Submission] David A. Viramontes Martinez

### ISSUE THREAD

**Issue by dviramontes** [astoria-tech/meetup#78]
### name

David A. Viramontes Martinez

### githubUsername

dviramontes

### linkedin

https://www.linkedin.com/in/davidviramontes/

### website

https://dviramontes.com

### presentationTitle

Leveraging Elixir as a two people development shop

### date

2024-06-05

### slides

[Leveraging Elixir as a two people development shop.pdf](https://github.com/astoria-tech/meetup/files/15184593/Leveraging.Elixir.as.a.two.people.development.shop.pdf)

### slidesSource

https://docs.google.com/presentation/d/17x7hhIiuE3ixv2SIhtdHoeR7DlmZ4_9_nJylCDGDEKI/edit?usp=sharing

**Comment by reggi** [comment]
.create-pr

**Comment by reggi** [comment]
.create-pr

**Comment by reggi** [comment]
.create-pr

**Comment by reggi** [comment]
.create-pr

**Comment by reggi** [comment]
.create-pr

**Comment by reggi** [comment]
.create-pr

**Comment by reggi** [comment]
.create-pr

**Comment by reggi** [comment]
.create-pr
