### ISSUE TITLE
[Talk Submission] Stefan Ciancio

### ISSUE THREAD

**Issue by lospoy** [astoria-tech/meetup#94]
### name

Stefan Ciancio

### linkedin

https://www.linkedin.com/in/stefan-ciancio-69955138/

### website

https://getwebinarkit.com

### profileImage

https://media.licdn.com/dms/image/C4E03AQGDfk2XtRmJ5Q/profile-displayphoto-shrink_800_800/0/1620917811884?e=1720051200&v=beta&t=An5h39S4CdZF8GGuJFv--NsUWzstaHRRb3O7m1aDEe8

### date

2024-06-05

**Comment by reggi** [comment]
.create-pr

**Comment by reggi** [comment]
.create-pr

**Comment by reggi** [comment]
.create-pr

**Comment by reggi** [comment]
.create-pr

**Comment by reggi** [comment]
.create-pr
